spring.application.name=spring-demo

# Import external env properties (sensitive DB settings)
spring.config.import=optional:classpath:env.properties

# Database configuration (Oracle via env.properties)
spring.datasource.url=${db.url}
spring.datasource.driver-class-name=${db.driver}
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true